### ISSUE TITLE
Update build script to support 0.2.0

### ISSUE THREAD

**Issue by saschanaz** [inflation/jpegxl-sys#1]
0.2 dropped:

* brunsli: https://gitlab.com/wg1/jpeg-xl/-/issues/95
* lcms2: https://gitlab.com/wg1/jpeg-xl/-/issues/50

Which means the corresponding rustc-link lines should be replaced.

There are [some build failures on Windows](https://gitlab.com/wg1/jpeg-xl/-/issues/104) that I have fixed in [my own branch](https://github.com/saschanaz/jpeg-xl/tree/build-fix), so probably a good idea to use it instead.

**Comment by inflation** [comment]
I wish to stick to the official repo as close as possible. It looks like both problems were fixed?

**Comment by saschanaz** [comment]
> I wish to stick to the official repo as close as possible. It looks like both problems were fixed? 

Same, but their fixes didn't make it to the repo yet, so I have to use my fork for now. It's just a small CMake change and submodule update. https://github.com/saschanaz/jpeg-xl/commits/build-fix

(Google is using their own private repo and "syncs" with the public one, but that hasn't happen yet.)
